### ISSUE TITLE
Emoji v13/v13.1/v14/v15/v15.1/v16 support

### ISSUE THREAD

**Issue by tdulcet** [rugk/awesome-emoji-picker#116]
Continuation of #34 and [Bug 1644346](https://bugzilla.mozilla.org/show_bug.cgi?id=1644346)

Blocked by:
- [x] https://github.com/missive/emoji-mart/issues/457

Also blocked in Firefox/Thunderbird by:
- [x] https://github.com/mozilla/twemoji-colr/issues/54
- [x] https://github.com/mozilla/twemoji-colr/issues/58 (Fixed in Firefox 92 in [Bug 1714632](https://bugzilla.mozilla.org/show_bug.cgi?id=1714632), uplifted to Firefox/Thunderbird 91)
- [x] https://github.com/mozilla/twemoji-colr/issues/64 (Fixed in Firefox 108 in [Bug 1761303](https://bugzilla.mozilla.org/show_bug.cgi?id=1761303))
- [ ] https://github.com/mozilla/twemoji-colr/issues/73 Emoji 15 and 15.1: [Bug 1796880](https://bugzilla.mozilla.org/show_bug.cgi?id=1796880) and [Bug 1824298](https://bugzilla.mozilla.org/show_bug.cgi?id=1824298)

We could also request that the future Firefox/Thunderbird updates be automated. See [here](https://groups.google.com/g/mozilla.dev.platform/c/y2IYnOEARc4) and [Bug 1618282](https://bugzilla.mozilla.org/show_bug.cgi?id=1618282).

**Comment by rugk** [comment]
For any user coming here: Here is a list of emojis that are not yet supported and would be with v13/v13.1:
* https://emojipedia.org/emoji-13.0/
* https://emojipedia.org/emoji-13.1/

**Comment by rugk** [comment]
> [bug 1644346](https://bugzilla.mozilla.org/show_bug.cgi?id=1644346)

OH thanks, did not even know I've created this bug?
Do you think it would be useful to create another one already now for Firefox and so on?

Or is the linked https://github.com/mozilla/twemoji-colr/issues/54 enough?

**Comment by tdulcet** [comment]
> Do you think it would be useful to create another one already now for Firefox and so on?
> 
> Or is the linked [mozilla/twemoji-colr#54](https://github.com/mozilla/twemoji-colr/issues/54) enough?

Considering that they were very responsive to your last bug, creating a new one may be a good idea. They seem to monitor BMO a lot more than that repository. It would need to be added before Firefox/Thunderbird 91, as otherwise TB and FF ESR users would have to wait a whole other year for Emoji v13…

**Comment by tdulcet** [comment]
> Do you think it would be useful to create another one already now for Firefox and so on?
> 
> Or is the linked [mozilla/twemoji-colr#54](https://github.com/mozilla/twemoji-colr/issues/54) enough?

Considering that they were very responsive to your last bug, creating a new one may be a good idea. They seem to monitor BMO a lot more than that repository. It would need to be added before Firefox/Thunderbird 91, as otherwise TB and FF ESR users would have to wait a whole other year for Emoji v13…

**Comment by tdulcet** [comment]
> Do you think it would be useful to create another one already now for Firefox and so on?
> 
> Or is the linked [mozilla/twemoji-colr#54](https://github.com/mozilla/twemoji-colr/issues/54) enough?

Considering that they were very responsive to your last bug, creating a new one may be a good idea. They seem to monitor BMO a lot more than that repository. It would need to be added before Firefox/Thunderbird 91, as otherwise TB and FF ESR users would have to wait a whole other year for Emoji v13…

**Comment by rugk** [comment]
BTW just want to note that on my Linux system (Fedora 34 Workstation) here I do see the 13.0 and 13.1 icons in v88.0.1 of Firefox. But I guess this is the system fallback and these are system emojis.

**Comment by rugk** [comment]
So here is the test file: https://gist.github.com/rugk/10131a881d73999bbd2493e935285dc9

(Download it and open it as a file in HTML)

So could you send me a screenshot of that broken emojis there?
And your system configuration?

Then I can report it. (Or you just do it by yourself)
I'm a little reluctant to report a bug that I cannot reproduce on my system.

**Comment by tdulcet** [comment]
> So here is the test file: https://gist.github.com/rugk/10131a881d73999bbd2493e935285dc9
> 
> (Download it and open it as a file in HTML)
> 
> So could you send me a screenshot of that broken emojis there, … @tdulcet?

That test file has the older v12 and v12.1 emojis. Here are two screenshots directly from your v13 Emojipedia link above.
![screenshot](https://user-images.githubusercontent.com/15305150/120625522-a4509080-c416-11eb-91fd-5959cdb2eda5.png)

> And your system configuration?

Ubuntu 20.04 with Firefox 89.0.

Also:
![image](https://user-images.githubusercontent.com/15305150/120621208-854fff80-c412-11eb-8c83-9e7aa7fb8169.png)

> And your system configuration?

Windows 10 version 1909 with Firefox 88.0.1.

According to those Emojipedia links, for desktop systems, only users with macOS 11 have the v13 emojis and only those with macOS 11.3 have the v13.1 emojis (it does not mention Linux). Therefore, users with Windows, older versions of macOS and probably most Linux distributions would not see these emojis.

**Comment by rugk** [comment]
oh sorry, here you go: https://gist.github.com/rugk/71cadef3b8a8f18909c4f3f4e649121e

It was indeed the wrong link.

As you can see, in Fedora it works :sweat_smile: :
![image](https://user-images.githubusercontent.com/11966684/120685416-19b47380-c4a0-11eb-9281-67be18614845.png)

**Comment by tdulcet** [comment]
> As you can see, in Fedora it works 😅 :

That is nice that it works for you! Fedora must have been very quick to implement them.

Here are the requested screenshots. Ubuntu 20.04:
![image](https://user-images.githubusercontent.com/15305150/120763690-5302d880-c4cc-11eb-8447-546e8511f28b.png)

Windows 10:
![image](https://user-images.githubusercontent.com/15305150/120763813-70d03d80-c4cc-11eb-9512-857cafee494e.png)

Both with Firefox 89.0, although I also tested with Firefox Nightly 91.

**Comment by rugk** [comment]
Okay, done. Reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1714632

**Comment by rugk** [comment]
Block in Firefox will be resolved in Firefox 92.

Now "only" blocked by missive/emoji-mart#457

**Comment by tdulcet** [comment]
> Block in Firefox will be resolved in Firefox 92.

They uplifted the change, so now the block will be [resolved in Firefox/Thunderbird 91](https://bugzilla.mozilla.org/show_bug.cgi?id=1714632#c16).

**Comment by Julianoe** [comment]
Hi just wanted to know what is lacking for this to be resolved?

**Comment by rugk** [comment]
The current state is shown in https://github.com/rugk/awesome-emoji-picker/pull/128, it's a big library upgrade, which unfortunately needs many internal changes on how the library is embedded etc. and I got stuck there.
